### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by MingHuiLiu** [asl97/ZEQ2-lite#1]
Building ZEQ2-Lite in Build/Release-linux-x86_64:
  PLATFORM: linux
  ARCH: x86_64
  VERSION: 1.36
  COMPILE_PLATFORM: linux
  COMPILE_ARCH: x86_64
  CC: cc

make[2]: Entering directory '/data/projects/ZEQ2-Lite-1'
make[2]: *** No rule to make target 'Build/Release-linux-x86_64/ded/null_client.o', needed by 'Build/Release-linux-x86_64/DedicatedServer.x86_64'。 停止。
make[2]: Leaving directory '/data/projects/ZEQ2-Lite-1'
Makefile:1182: recipe for target 'targets' failed
make[1]: *** [targets] Error 2
make[1]: Leaving directory '/data/projects/ZEQ2-Lite-1'
Makefile:1133: recipe for target 'release' failed

**Comment by MingHuiLiu** [comment]
@asl97

**Comment by asl97** [comment]
This is just a unofficial mirror,  If master branch ain't building,  check upstream.

Otherwise, use the tagged release https://github.com/asl97/ZEQ2-lite/tree/Revision-1536 .
